
module.exports = [
  {category: 'Electronics', price: '$19.99', stocked: true, name: 'careless'},
  {category: 'Electronics', price: '$19.99', stocked: true, name: 'geese'},
  {category: 'Electronics', price: '$19.99', stocked: true, name: 'early'},
  {category: 'Electronics', price: '$29.99', stocked: false, name: 'silent'},
  {category: 'Electronics', price: '$19.99', stocked: true, name: 'entertain'},
  {category: 'Electronics', price: '$19.99', stocked: true, name: 'general'},
  {category: 'Electronics', price: '$19.99', stocked: true, name: 'reason'},
  {category: 'Electronics', price: '$39.99', stocked: true, name: 'assorted'},
  {category: 'Electronics', price: '$19.99', stocked: true, name: 'wait'},
  {category: 'Electronics', price: '$29.99', stocked: false, name: 'funny'},
  {category: 'Electronics', price: '$19.99', stocked: false, name: 'noiseless'},
  {category: 'Electronics', price: '$19.99', stocked: true, name: 'handsomely'},
  {category: 'Electronics', price: '$19.99', stocked: true, name: 'burst'},
  {category: 'Electronics', price: '$19.99', stocked: true, name: 'mend'},
  {category: 'Electronics', price: '$39.99', stocked: true, name: 'laugh'},
  {category: 'Electronics', price: '$19.99', stocked: true, name: 'strong'},
  {category: 'Electronics', price: '$19.99', stocked: false, name: 'beneficial'},
  {category: 'Food', price: '$29.99', stocked: false, name: 'vivacious'},
  {category: 'Food', price: '$19.99', stocked: false, name: 'better'},
  {category: 'Food', price: '$39.99', stocked: true, name: 'soak'},
  {category: 'Food', price: '$19.99', stocked: true, name: 'straight'},
  {category: 'Food', price: '$19.99', stocked: true, name: 'obese'},
  {category: 'Food', price: '$19.99', stocked: true, name: 'nebulous'},
  {category: 'Food', price: '$39.99', stocked: false, name: 'grab'},
  {category: 'Food', price: '$29.99', stocked: false, name: 'report'},
  {category: 'Food', price: '$19.99', stocked: false, name: 'understood'},
  {category: 'Food', price: '$19.99', stocked: true, name: 'meeting'},
  {category: 'Food', price: '$19.99', stocked: true, name: 'whirl'},
  {category: 'Food', price: '$19.99', stocked: true, name: 'past'},
  {category: 'Food', price: '$39.99', stocked: true, name: 'ray'},
  {category: 'Food', price: '$29.99', stocked: true, name: 'growth'},
  {category: 'Food', price: '$19.99', stocked: false, name: 'colossal'},
  {category: 'Other random category', price: '$19.99', stocked: false, name: 'adjoining'},
  {category: 'Other random category', price: '$19.99', stocked: false, name: 'bat'},
  {category: 'Other random category', price: '$19.99', stocked: true, name: 'mindless'},
  {category: 'Other random category', price: '$19.99', stocked: true, name: 'efficacious'},
  {category: 'Other random category', price: '$19.99', stocked: true, name: 'number'},
  {category: 'Other random category', price: '$29.99', stocked: true, name: 'sweltering'},
  {category: 'Other random category', price: '$39.99', stocked: true, name: 'well-made'},
  {category: 'Other random category', price: '$39.99', stocked: false, name: 'license'},
  {category: 'Other random category', price: '$19.99', stocked: false, name: 'trip'},
  {category: 'Other random category', price: '$19.99', stocked: false, name: 'feeble'},
  {category: 'Other random category', price: '$19.99', stocked: true, name: 'dashing'},
  {category: 'Other random category', price: '$29.99', stocked: true, name: 'railway'},
  {category: 'More?', price: '$19.99', stocked: true, name: 'harmonious'},
  {category: 'More?', price: '$19.99', stocked: true, name: 'skate'},
  {category: 'More?', price: '$19.99', stocked: true, name: 'increase'},
  {category: 'More?', price: '$19.99', stocked: false, name: 'fuel'},
  {category: 'More?', price: '$39.99', stocked: false, name: 'mailbox'},
  {category: 'More?', price: '$19.99', stocked: false, name: 'bed'},
  {category: 'More?', price: '$29.99', stocked: true, name: 'crib'},
  {category: 'More?', price: '$19.99', stocked: true, name: 'part'},
  {category: 'More?', price: '$19.99', stocked: true, name: 'fairies'},
  {category: 'More?', price: '$19.99', stocked: true, name: 'trees'},
  {category: 'More?', price: '$39.99', stocked: false, name: 'strip'},
  {category: 'More?', price: '$29.99', stocked: false, name: 'annoying'},
  {category: 'More?', price: '$19.99', stocked: false, name: 'pull'},
  {category: 'More?', price: '$19.99', stocked: true, name: 'pleasant'},
  {category: 'More?', price: '$19.99', stocked: true, name: 'downtown'},
  {category: 'More?', price: '$19.99', stocked: true, name: 'elfin'},
  {category: 'More?', price: '$29.99', stocked: true, name: 'cheese'},
  {category: 'More?', price: '$19.99', stocked: false, name: 'surround'},
  {category: 'More?', price: '$19.99', stocked: false, name: 'pour'},
  {category: 'More?', price: '$19.99', stocked: true, name: 'smooth'},
  {category: 'This is way to much', price: '$39.99', stocked: true, name: 'anger'},
  {category: 'This is way to much', price: '$29.99', stocked: true, name: 'enthusiastic'},
  {category: 'This is way to much', price: '$19.99', stocked: true, name: 'basket'},
  {category: 'This is way to much', price: '$39.99', stocked: true, name: 'neighborly'},
  {category: 'This is way to much', price: '$19.99', stocked: true, name: 'trashy'},
  {category: 'This is way to much', price: '$19.99', stocked: true, name: 'insurance'},
  {category: 'This is way to much', price: '$19.99', stocked: false, name: 'abiding'},
  {category: 'This is way to much', price: '$29.99', stocked: false, name: 'nut'},
  {category: 'This is way to much', price: '$19.99', stocked: false, name: 'infamous'},
  {category: 'This is way to much', price: '$19.99', stocked: true, name: 'risk'},
  {category: 'This is way to much', price: '$19.99', stocked: true, name: 'wrench'},
  {category: 'This is way to much', price: '$39.99', stocked: true, name: 'volcano'},
  {category: 'This is way to much', price: '$29.99', stocked: true, name: 'share'},
  {category: 'This is way to much', price: '$19.99', stocked: false, name: 'alive'},
  {category: 'This is way to much', price: '$19.99', stocked: false, name: 'exercise'},
  {category: 'This is way to much', price: '$19.99', stocked: true, name: 'haunt'},
  {category: 'This is way to much', price: '$39.99', stocked: true, name: 'detect'},
  {category: 'This is way to much', price: '$39.99', stocked: false, name: 'money'},
  {category: 'This is way to much', price: '$19.99', stocked: false, name: 'torpid'},
  {category: 'Seriously, over the top', price: '$29.99', stocked: false, name: 'appear'},
  {category: 'Seriously, over the top', price: '$19.99', stocked: true, name: 'elbow'},
  {category: 'Seriously, over the top', price: '$19.99', stocked: true, name: 'measly'},
  {category: 'Seriously, over the top', price: '$39.99', stocked: false, name: 'giants'},
  {category: 'Seriously, over the top', price: '$19.99', stocked: false, name: 'rambunctious'},
  {category: 'Seriously, over the top', price: '$19.99', stocked: true, name: 'busy'},
  {category: 'Seriously, over the top', price: '$19.99', stocked: true, name: 'authority'},
  {category: 'Seriously, over the top', price: '$29.99', stocked: true, name: 'frighten'},
  {category: 'Seriously, over the top', price: '$19.99', stocked: true, name: 'space'},
  {category: 'Seriously, over the top', price: '$39.99', stocked: true, name: 'innate'},
  {category: 'Seriously, over the top', price: '$19.99', stocked: true, name: 'suggest'},
  {category: 'Seriously, over the top', price: '$19.99', stocked: true, name: 'panoramic'},
  {category: 'Seriously, over the top', price: '$29.99', stocked: false, name: 'pie'},
  {category: 'Seriously, over the top', price: '$19.99', stocked: false, name: 'earthquake'},
  {category: 'Seriously, over the top', price: '$39.99', stocked: false, name: 'wriggle'},
  {category: 'Seriously, over the top', price: '$19.99', stocked: true, name: 'eight'},
  {category: 'Seriously, over the top', price: '$19.99', stocked: true, name: 'rose'},
];
